apiVersion: v1
kind: Secret
metadata:
    name: keycloak-idp-credentials
    namespace: identity
type: Opaque
stringData:
    google-client-secret: ENC[AES256_GCM,data:DGfvrhHN9WLlQfM8t8iFWr2vVfIzfxWK3aXH6/PVS9oToAI=,iv:/3KSOlB+YUZGjG3RmwKZDy+tM1uAKjYcYuV7UNKpbUY=,tag:c+03vlJaI11e0AQTmfLCTw==,type:str]
    test-user-password: ENC[AES256_GCM,data:yd3FDosGF7aVxHEI6JD/cC8kJgmy6v3WjJfKZS2Zsoc=,iv:xmJLAzTWN65E/L1EqErj0fgHcjdV/qBKuzlZCRv0c5E=,tag:gx06DNeL3s6CBIw7qajIOQ==,type:str]
sops:
    age:
        - recipient: age1a8ql96ddfajj4zkuecs8vnafld9sls7cx4czrydtjn6qqsc6c9gspx8c9l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDY3NLamFNNDI5MW9tazdZ
            TmczbFN4TDNIV3V1S3V2aHRLSW5wN0FEdTA0CkFlNmhPVVNWOE8yWFV0NUNvMDlG
            YWtaUDExZE5tZVBGUDZ5dEtENGg2ZzQKLS0tIG54R09LZkNnelQ0T2dwVmdPenFJ
            Z1UyeVF2K2M0dXgyWVd1NXRCNjRDTDAKZoBBQn8X8fhQFGz0NrPX/n2HvPhHZS8y
            IfyZdS/Tn8j3mbQSMhjcswHphPhZxFOnj/DZoeezSBGbYChpL2CmAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T20:12:35Z"
    mac: ENC[AES256_GCM,data:t/Pus7A22ikKYHgzEl4dBMJkB9bKZ/D16dfQNYzFEphKFeZeAec3bPkx3s7FDppavI1aUOxz/LhshBIiSYpKxMrWe0ydcuLtD4qHPLm+nmnl5IkgzH31pDhI0UAB8Tg4ICUEc0vJWSqotbdVzDFAOotFMhZFG1hMxHwUPqDkwJY=,iv:4teSUXmWT828TMtKxIxlWGIpxUoCUjA4guLTR6VQ6SQ=,tag:T/VAtlihi9991Q5zeJCqTw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
