---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager-config-kustomization.yaml
  - gateway-api-crds-kustomization.yaml
  - ingress-stack-kustomization.yaml
  - ingress-config-kustomization.yaml
  - identity-routes-kustomization.yaml
  - minio-routes-kustomization.yaml
  - metallb-config-kustomization.yaml
  - ../../infrastructure
  - ../../apps
