apiVersion: v1
kind: Secret
metadata:
    name: keycloak-admin-credentials
    namespace: identity
type: Opaque
stringData:
    admin-password: ENC[AES256_GCM,data:kIND9mj9+8WS75GyFUhHWiER3CX0MKPFi3tUi1ZyWWlIel+CzAKYsAIjOgk=,iv:YXYl5oyfFRgk63IU6VcGtSFzZXJjFMKwLsvrce4IDpk=,tag:BpMg619S6Pg8rkfbT+CFeA==,type:str]
sops:
    age:
        - recipient: age1a8ql96ddfajj4zkuecs8vnafld9sls7cx4czrydtjn6qqsc6c9gspx8c9l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUZFNVTjh3TGkycXdJUzM2
            a0hIT3VIZ2lnem9yVnlORWhaNTJRVlh6VHkwCmVZRHJZUXBROUNWeGY5Z3pMYUxB
            Zno4L3MrUTgvY0d0Y3hrcExhT1haWGcKLS0tIGdmS0xTN04vWE1Canh0bzQrRHRU
            Z2ZlYVU5S1BCU3MzMDJlKzNCNklJYnMK4wAMtC+vu2e1n+f2S59Ll4qbbUOC4qr2
            ejs82PAP2Kr2aDFhkTik4dwgPcSMIwcRH0beB/gX5c1PDlxB2O3OlQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-05T19:26:33Z"
    mac: ENC[AES256_GCM,data:e9N3iW3sOzw3AP483K1EM4M2Ban9sHpfnjGtUNENbG9Rctil5Ky3sqUDlX+sNkNSoTIR+AxGuWCtGCyK/ie6VTBmL/u4HWJynFCVTf0uflWHHgsWtK8OGYv3G/S878fAhAXmdpCO9/m5T5VS/7AWr/SJHiMNuFz7Wc3U/uHExUU=,iv:0aOoY3/DNeBIS2XtFVz40zaJpfL1YoSSc/6guPD1O4g=,tag:vYY71csKc6W509vr2BK1tg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: keycloak-postgresql-credentials
    namespace: identity
type: Opaque
stringData:
    postgres-password: ENC[AES256_GCM,data:VgIN/SIPht5d1lTIZUTte3DTA4CVJuwLOj1MJyFZhC/XPKnnlXe8WXFKM8E=,iv:O/JF/UDraGZoQFVTBUg2EkXUy8tItD2EnxU/bMvGr5M=,tag:tYSQWPtRT251jnEvP7DVRQ==,type:str]
    password: ENC[AES256_GCM,data:nhvywha6a7wiCx7VT9v2/vHO1QEZVfkWGtZb4FFD50zCAB5TRuc+jwgiSTo=,iv:WmijQp7FlgndzbKCKhLVjBASsGpc+vJYtjfVE44Z0fc=,tag:8nxYqlPz6Py6qk+Jm/vLXw==,type:str]
sops:
    age:
        - recipient: age1a8ql96ddfajj4zkuecs8vnafld9sls7cx4czrydtjn6qqsc6c9gspx8c9l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUZFNVTjh3TGkycXdJUzM2
            a0hIT3VIZ2lnem9yVnlORWhaNTJRVlh6VHkwCmVZRHJZUXBROUNWeGY5Z3pMYUxB
            Zno4L3MrUTgvY0d0Y3hrcExhT1haWGcKLS0tIGdmS0xTN04vWE1Canh0bzQrRHRU
            Z2ZlYVU5S1BCU3MzMDJlKzNCNklJYnMK4wAMtC+vu2e1n+f2S59Ll4qbbUOC4qr2
            ejs82PAP2Kr2aDFhkTik4dwgPcSMIwcRH0beB/gX5c1PDlxB2O3OlQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-05T19:26:33Z"
    mac: ENC[AES256_GCM,data:e9N3iW3sOzw3AP483K1EM4M2Ban9sHpfnjGtUNENbG9Rctil5Ky3sqUDlX+sNkNSoTIR+AxGuWCtGCyK/ie6VTBmL/u4HWJynFCVTf0uflWHHgsWtK8OGYv3G/S878fAhAXmdpCO9/m5T5VS/7AWr/SJHiMNuFz7Wc3U/uHExUU=,iv:0aOoY3/DNeBIS2XtFVz40zaJpfL1YoSSc/6guPD1O4g=,tag:vYY71csKc6W509vr2BK1tg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: keycloak-external-db-credentials
    namespace: identity
type: Opaque
stringData:
    db-user: ENC[AES256_GCM,data:ZRhrxf6h688=,iv:Q215Hb7eZyqnSNWx0VZSAxjgHLo7GjIigJ8MnD3tEKc=,tag:9tZXl8NomdHji6KLGBG9qQ==,type:str]
    db-password: ENC[AES256_GCM,data:UJ34i63A1I5jYAlBUIbLzfE5Yld9uDh9C1IFEQ3JeLS6kV0L9eXOcqi7Xr8=,iv:5Wf3oJ+TQmtLhzJEgQE1tplkF0QDKjYm/dvBFlBzJt0=,tag:U9IjeOnCVHGWwHU4RBGOiw==,type:str]
sops:
    age:
        - recipient: age1a8ql96ddfajj4zkuecs8vnafld9sls7cx4czrydtjn6qqsc6c9gspx8c9l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUZFNVTjh3TGkycXdJUzM2
            a0hIT3VIZ2lnem9yVnlORWhaNTJRVlh6VHkwCmVZRHJZUXBROUNWeGY5Z3pMYUxB
            Zno4L3MrUTgvY0d0Y3hrcExhT1haWGcKLS0tIGdmS0xTN04vWE1Canh0bzQrRHRU
            Z2ZlYVU5S1BCU3MzMDJlKzNCNklJYnMK4wAMtC+vu2e1n+f2S59Ll4qbbUOC4qr2
            ejs82PAP2Kr2aDFhkTik4dwgPcSMIwcRH0beB/gX5c1PDlxB2O3OlQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-05T19:26:33Z"
    mac: ENC[AES256_GCM,data:e9N3iW3sOzw3AP483K1EM4M2Ban9sHpfnjGtUNENbG9Rctil5Ky3sqUDlX+sNkNSoTIR+AxGuWCtGCyK/ie6VTBmL/u4HWJynFCVTf0uflWHHgsWtK8OGYv3G/S878fAhAXmdpCO9/m5T5VS/7AWr/SJHiMNuFz7Wc3U/uHExUU=,iv:0aOoY3/DNeBIS2XtFVz40zaJpfL1YoSSc/6guPD1O4g=,tag:vYY71csKc6W509vr2BK1tg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
