apiVersion: v1
kind: Secret
metadata:
    name: minio-root-credentials
    namespace: minio
type: Opaque
data:
    rootUser: ENC[AES256_GCM,data:sMNuW1fg69rMmEQBnWbZrQ==,iv:TnKl+2hJZCQkmhHudhCvbUCYMc2oiob+sqzF1xLNGYA=,tag:2sahwzJZ4O2YiP4B8w0+XQ==,type:str]
    rootPassword: ENC[AES256_GCM,data:QR68bkkKmbP6B409y3vU8ynxaC2UrwtscwMsRnHguCyKbzQTBOr+cvMX/WZ6UtJ6h4+iAIUu7AL9wWvdOj/n6g==,iv:bK/xm71yS+9H/mjky4nwXJdk3CrNuF0mWNgB72eSE48=,tag:irMMrhb0Wv4qpRsRiVDQVg==,type:str]
sops:
    age:
        - recipient: age1a8ql96ddfajj4zkuecs8vnafld9sls7cx4czrydtjn6qqsc6c9gspx8c9l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxWXNUbWZ1ME5rV2RhMkpq
            RE9la2xRVEFnUjdteHZEVW16VXliakt3NlQ0CnAwZ01EYU42RFlwWXVxdkQxTUlz
            emxPZ2hhTkxHRG5yTUIrRWRET0F1V1EKLS0tIFFsZnpiTE5qWS91eEJvekNzTmtk
            Mk0wNHA0dktxQWxmQ0xzckNrb0xWNTgKhyK8t946SYmfc+799HvCYzSbiYR4rKGa
            uorZ8c5hiz//65588Mizgsm2/tAHhrAibjLTbthtPRC05WRjOc8YQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-03T15:08:42Z"
    mac: ENC[AES256_GCM,data:GGKV5sryjjjzaRYYzZ6cNTnEA3kaiSGsfRloMgk8mXBvAMootKdMhYPdlCjzMiozt/TnaN927la1Q8MOJA6vEUZRNovXIju7kxeFODHB8W7W2LgjmxUVMf4SFMIP7PnDyVq4Qatjrm4iistSEnSvZLEn9Bj7RQpWD0sD9gfIRR4=,iv:MW1JXsUoeToG5zW2rUs26eQTb34UTQ2sp/FtHfxkTNA=,tag:3ZyqKp9PWvlvfVFpMs2eGA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
