apiVersion: v1
kind: Secret
metadata:
    name: minio-root-credentials
    namespace: minio
type: Opaque
stringData:
    rootUser: ENC[AES256_GCM,data:755hSpi1E/R/qA==,iv:RBGw9rWK6zaCKv8N9XzvGR6t089fnbYg/kfJggmMS1I=,tag:BmcZHJvJ9JHzHUb5jbAQpg==,type:str]
    rootPassword: ENC[AES256_GCM,data:AOt9dQ0uLpxQ8KeTz6SxWqk3CDsd9JuwFGEDcUumokarqN1vbqxlY9EYEoDluJz8,iv:dMFEFXvjjVHvonqCmOfNFe3mjyH610t/+Ne9Kn/S5J8=,tag:7gqz8flS4n+N4MB4jsYO5g==,type:str]
sops:
    age:
        - recipient: age1a8ql96ddfajj4zkuecs8vnafld9sls7cx4czrydtjn6qqsc6c9gspx8c9l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPYjhYQXZUMytIM0F6UDhQ
            QmxjbHV5WDBjYVM4eGN6b05va2ZyWFpBNW1jCmxYclQ1clJDZTFTYVVvcXpUMHVN
            N2FTWEtRamJxUElHUUtyR0ptN1NBeG8KLS0tIHh4TjdUT0xhK3BPVjBld0JWTzhD
            Yk9YQTVsRnlONU1Lby82SjN2dmJGT1EKPVO9I9R6BXn6eFSUP3qdU3mx6Kq7V+WX
            YSMKUc+iChEoelh7RyS1e7elz3GVUh70KH9cUQ0LdkTSN0+sk2/9iA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-03T14:14:24Z"
    mac: ENC[AES256_GCM,data:w6H/wTJn/BcUdT1SD1TWMB9zh+nzmUZztrL68iRorZARVuFENWlqToM+i0Qkq/cTNYfsiiYxnaB/1mrInD+6X5RqzP3Cfb7b/LzNXb/sTolnnD6x9i2WgvpM0eRSZg00e2De7T1cNovhCNhVx4j8lGejDbf7pl4adavBfeX0rNA=,iv:86+A/Y0k63gsV6sPauBlSWzfVQC3uDBlC/sHoyB6+6Q=,tag:tRDAOdJ0AYMrfsSstxtjuA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
