apiVersion: v1
kind: Secret
metadata:
    name: azuredns-credentials
    namespace: cert-manager
type: Opaque
stringData:
    client-secret: ENC[AES256_GCM,data:Xw28GNOlMio+8l20R/YJc0C8/2iWJs904RLTyASsnFlZcSlh95aJeA==,iv:nrCh2VMj+DMs1zIc1y7VoY17hbnGUD8HAWnHwkBG4jY=,tag:ONpg5gZoIfiND1304EdREA==,type:str]
sops:
    age:
        - recipient: age1a8ql96ddfajj4zkuecs8vnafld9sls7cx4czrydtjn6qqsc6c9gspx8c9l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXeER5RVNSa3h4RThvTzdC
            L3I2S0xQU1k3dlh6UmNGVzFpSDE0TVJJRFRBCnRpTjd4VFhtK0JSZi9pMTZ6Ri9T
            SnB3eXpUdXF1ZGRoZWEzUFFhcVVUaDgKLS0tIHYvYytRL2hYWlhzUWE3VXJIaXdT
            WnRHSk42cEJrUGErTDF1ci9kNitwNFEK+6gNm7gfkvJOU+BKVCyI859Uean91Hej
            fBJDvf32OMSUac9pFuR1bsNfdqMWqUhYCx8CdcGgO7aVBp+t/KKmyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-04T19:46:59Z"
    mac: ENC[AES256_GCM,data:DSSOl+8CLgRdaAc9YAzEpQmPKYSEHq6PsolbI8CxHdFW2NxtdLxT7eHoW/efNBIkpWmTQSecHSZMR2Uk0acpLDFGNX5+kxaylIRAWj2Gl+KK56dOmb8UzmVqRx05VHke2YvQtAkxGsRE0+c2QniiCX9WOczZJ4fCZinqkfGECuI=,iv:uJodlSYJm+9ZxAaOMEUgregzD7B5jBbc/+W92ezmGIg=,tag:/eBNUbrAhrMj8NfYjMs3Gg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
