defaults:
  user: ubuntu
  identity_file: ~/.ssh/github_id

hosts:
  - name: pve-01
    ip: 192.168.0.100
    aliases:
      - pve-01.lan
    user: root
  - name: k8s-control-01
    ip: 192.168.0.110
    aliases:
      - control-01
    user: dmgiangi
  - name: k8s-worker-01
    ip: 192.168.0.120
    aliases:
      - worker-01
    user: dmgiangi